# theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
title: Giulia Grisot, PhD
logo: /images/sketch.png
description: Giulia Grisot's personal webpage
color_scheme: Yellow
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  "GitHub Repository":
    - "https://github.com/giuliagrisot"
# footer_content:
# quick_links:
#   - name: Reading List
#     url: "https://docs.google.com/document/d/1qJCaaOtJ2z5eC7Iodvz8NAmD8FDbXJD9YqLPmdXRbDE/edit?usp=sharing"
#   - name: Google Drive
#     url: "https://drive.google.com/drive/folders/13i2Sor2M7it72aGlMd87Iejw6fzqsBxI?usp=sharing"
#   - name: MS Teams
#     url: "https://teams.microsoft.com/l/team/19%3ait66PgoRabiGRMhXIEr67O1_XTkjExhyqn3rxIf2vI81%40thread.tacv2/conversations?groupId=d69b57e3-80a0-4b92-88fb-a54bd9145bab&tenantId=5217e0e7-539d-4563-b1bf-7c6dcf074f91"
