theme: jekyll-theme-minimal
title: Distant Reading Basel
logo: /images/homepage.jpg
description: Homepage of the project "High Mountains Low Arousal? Distant Reading Topographies of Sentiment in German Swiss Novels in the early 20th Century" 
