# theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
title: Giulia Grisot, Ph.D.
color_scheme: my_color_scheme
logo: /images/sketch.png
description: My personal webpage
url: https://giuliagrisot.github.io/
aux_links:
  "GitHub Repository":
    - "https://github.com/giuliagrisot"
# footer_content:
quick_links:
   - name: ResearchGate
     url: "https://www.researchgate.net/profile/Giulia-Grisot"
   - name: ORCID
     url: "https://orcid.org/my-orcid?orcid=0000-0002-3038-6202"
   - name: Twitter
     url: "https://twitter.com/Grig_gg"
